---
title: "Homework 2"
author: Julia Gray
output: github_document
date: "09-24-25"
---
```{r echo=TRUE, message=FALSE}
library(tidyverse)
```

## Problem 1

Import and clean pos_month data
```{r message=FALSE}
pos_month_df = read_csv(file="./data/fivethirtyeight_datasets/pols-month.csv") |> 
  janitor::clean_names() |> 
  separate(
    col="mon",
    into=c("year", "month", "day"),
    sep="-"
  ) |> 
  mutate(
    month = 
      case_match(
        month, 
        "01" ~ "jan", 
        "02" ~ "feb",
        "03" ~ "mar",
        "04" ~ "apr", 
        "05" ~ "may",
        "06" ~ "jun",
        "07" ~ "jul",
        "08" ~ "aug",
        "09" ~ "sep",
        "10" ~ "oct",
        "11" ~ "nov",
        "12" ~ "dec") 
    ) |> 
  mutate(
    president = case_when(
      prez_gop == 1 ~ "gop",
      prez_dem == 1 ~ "dem"
    )
  ) |> 
  select(-day, -prez_dem, -prez_gop) |> 
  mutate(year = as.integer(year))
```

Double check if in original dataframe there are any rows where both prez_gop and prez_dem == 1

```{r message=FALSE}
filter(
  read_csv(file="./data/fivethirtyeight_datasets/pols-month.csv"), 
  prez_gop == 1, prez_dem == 1)
```

Import and clean snp data
```{r message=FALSE}
snp_df = read_csv(file="./data/fivethirtyeight_datasets/snp.csv") |> 
  separate(
    col = "date",
    into = c("month", "day", "year"),
    sep = "/"
  ) |>
  #in order to correctly sort we need to recast the strings for year and month as integers
  mutate(
    year = case_when(
      as.integer(year) <= 15 ~ as.integer(year) + 2000,
      as.integer(year) > 15 ~ as.integer(year) + 1900
    ),
    month = as.integer(month)
  ) |> 
  relocate("year", "month",  "day") |> 
  arrange(year, month, day) |> 
  #now that we've arranged year and month we can change month number month name to match pos_month_df
  mutate(
    month = 
      case_match(
        month, 
        1 ~ "jan", 
        2 ~ "feb",
        3 ~ "mar",
        4 ~ "apr", 
        5 ~ "may",
        6 ~ "jun",
        7 ~ "jul",
        8 ~ "aug",
        9 ~ "sep",
        10 ~ "oct",
        11 ~ "nov",
        12 ~ "dec") 
    ) |> 
  select(-day)
```

Import and tidy unemployment data

```{r}
unemployment_df = read_csv(file="./data/fivethirtyeight_datasets/unemployment.csv") |> 
  janitor::clean_names()
```






